import Foundation

class EspressoGenerator: CodeGenerationStrategy {
    func generate(
        flowGroup: FlowGroup,
        screens: [CapturedScreen],
        edges: [NavigationEdge],
        bundleID: String
    ) -> String {
        var code = """
        package com.example.tests

        import androidx.test.ext.junit.rules.ActivityScenarioRule
        import androidx.test.ext.junit.runners.AndroidJUnit4
        import androidx.test.espresso.Espresso.onView
        import androidx.test.espresso.action.ViewActions.*
        import androidx.test.espresso.matcher.ViewMatchers.*
        import org.hamcrest.Matchers.allOf
        import org.junit.Rule
        import org.junit.Test
        import org.junit.runner.RunWith

        /**
         * Generated by Xamrock Studio
         * Flow: \(flowGroup.name)
         */
        @RunWith(AndroidJUnit4::class)
        class \(CodeGenerationUtilities.sanitizeClassName(flowGroup.name))Test {

            @get:Rule
            val activityRule = ActivityScenarioRule(MainActivity::class.java)

            @Test
            fun test\(CodeGenerationUtilities.sanitizeFunctionName(flowGroup.name))() {

        """

        let flowScreens = screens.filter { screen in
            screen.flowGroupIds.contains(flowGroup.id)
        }

        let path = CodeGenerationUtilities.buildTestPath(screens: flowScreens, edges: edges)

        for step in path {
            code += generateStep(step, indentation: "        ")
        }

        code += """
            }
        }

        """

        return code
    }

    private func generateStep(_ step: TestStep, indentation: String) -> String {
        var code = "\n"
        code += "\(indentation)// \(step.description)\n"

        switch step.action {
        case .tap(let identifier, let label):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(click())\n"
            } else if !label.isEmpty {
                code += "\(indentation)onView(withText(\"\(escapeString(label))\"))\n"
                code += "\(indentation)    .perform(click())\n"
            } else {
                code += "\(indentation)// TODO: Tap element (identifier unknown)\n"
            }

        case .typeText(let identifier, let text):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(click())\n"
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(typeText(\"\(escapeString(text))\"))\n"
            } else {
                code += "\(indentation)// TODO: Type text '\(text)' (identifier unknown)\n"
            }

        case .wait(let seconds):
            code += "\(indentation)Thread.sleep(\(Int(seconds * 1000)))\n"

        case .verify(let condition):
            code += "\(indentation)// TODO: Verify \(condition)\n"

        case .swipe(let direction, let identifier, let label):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(swipe\(direction.rawValue.capitalized)())\n"
            } else if !label.isEmpty {
                code += "\(indentation)onView(withText(\"\(escapeString(label))\"))\n"
                code += "\(indentation)    .perform(swipe\(direction.rawValue.capitalized)())\n"
            } else {
                code += "\(indentation)// Swipe \(direction.rawValue) on screen\n"
                code += "\(indentation)onView(isRoot()).perform(swipe\(direction.rawValue.capitalized)())\n"
            }

        case .longPress(let identifier, let label, let duration):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(longClick())\n"
            } else if !label.isEmpty {
                code += "\(indentation)onView(withText(\"\(escapeString(label))\"))\n"
                code += "\(indentation)    .perform(longClick())\n"
            } else {
                code += "\(indentation)// TODO: Long press element (identifier unknown)\n"
            }

        case .doubleTap(let identifier, let label):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(doubleClick())\n"
            } else if !label.isEmpty {
                code += "\(indentation)onView(withText(\"\(escapeString(label))\"))\n"
                code += "\(indentation)    .perform(doubleClick())\n"
            } else {
                code += "\(indentation)// TODO: Double tap element (identifier unknown)\n"
            }

        case .tapCoordinate(let x, let y):
            code += "\(indentation)// TODO: Tap at coordinate (\(Int(x)), \(Int(y)))\n"
            code += "\(indentation)// Note: Coordinate-based taps require custom implementation in Espresso\n"

        case .tapCell(let index, let identifier, let label):
            if !identifier.isEmpty && identifier != "manual_edge" {
                code += "\(indentation)onView(withId(R.id.\(sanitizeResourceID(identifier))))\n"
                code += "\(indentation)    .perform(scrollToPosition(\(index)))\n"
                code += "\(indentation)onData(anything())\n"
                code += "\(indentation)    .atPosition(\(index))\n"
                code += "\(indentation)    .perform(click())\n"
            } else if !label.isEmpty {
                code += "\(indentation)onView(withText(\"\(escapeString(label))\"))\n"
                code += "\(indentation)    .perform(click())\n"
            } else {
                code += "\(indentation)// TODO: Tap cell at index \(index)\n"
            }
        }

        return code
    }

    private func sanitizeResourceID(_ id: String) -> String {
        // Remove package name prefix if present (e.g., "com.example:id/button" -> "button")
        if let colonIndex = id.lastIndex(of: ":"),
           let slashIndex = id.lastIndex(of: "/") {
            let afterSlash = id.index(after: slashIndex)
            return String(id[afterSlash...])
        }

        // Convert to valid Kotlin identifier
        var sanitized = id.replacingOccurrences(of: "-", with: "_")
        sanitized = sanitized.replacingOccurrences(of: ".", with: "_")
        sanitized = sanitized.replacingOccurrences(of: " ", with: "_")

        // Ensure it doesn't start with a number
        if let firstChar = sanitized.first, firstChar.isNumber {
            sanitized = "_" + sanitized
        }

        return sanitized
    }

    private func escapeString(_ str: String) -> String {
        return str
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }
}
