import Foundation

class MaestroGenerator: CodeGenerationStrategy {
    func generate(
        flowGroup: FlowGroup,
        screens: [CapturedScreen],
        edges: [NavigationEdge],
        bundleID: String
    ) -> String {
        var yaml = """
        appId: \(bundleID)
        ---
        # Flow: \(flowGroup.name)
        # Generated by Studio

        """

        let flowScreens = screens.filter { screen in
            screen.flowGroupIds.contains(flowGroup.id)
        }

        let path = CodeGenerationUtilities.buildTestPath(screens: flowScreens, edges: edges)

        for step in path {
            yaml += generateStep(step)
        }

        return yaml
    }

    private func generateStep(_ step: TestStep) -> String {
        var yaml = ""
        yaml += "# \(step.description)\n"

        switch step.action {
        case .tap(let identifier, let label):
            if !label.isEmpty {
                yaml += "- tapOn: \"\(label)\"\n"
            } else if !identifier.isEmpty && identifier != "manual_edge" {
                yaml += "- tapOn:\n"
                yaml += "    id: \"\(identifier)\"\n"
            } else {
                yaml += "# TODO: Tap action (identifier unknown)\n"
            }

        case .typeText(let identifier, let text):
            yaml += "- tapOn:\n"
            yaml += "    id: \"\(identifier)\"\n"
            yaml += "- inputText: \"\(text)\"\n"

        case .wait(let seconds):
            yaml += "- wait: \(Int(seconds * 1000))ms\n"

        case .verify(let condition):
            yaml += "# TODO: Verify \(condition)\n"

        case .swipe(let direction, let identifier, let label):
            yaml += "- swipe:\n"
            yaml += "    direction: \(direction.rawValue.uppercased())\n"
            if !identifier.isEmpty && identifier != "manual_edge" {
                yaml += "    id: \"\(identifier)\"\n"
            } else if !label.isEmpty {
                yaml += "    text: \"\(label)\"\n"
            }

        case .longPress(let identifier, let label, let duration):
            yaml += "- longPressOn:\n"
            if !identifier.isEmpty && identifier != "manual_edge" {
                yaml += "    id: \"\(identifier)\"\n"
            } else if !label.isEmpty {
                yaml += "    text: \"\(label)\"\n"
            }
            yaml += "    duration: \(Int(duration * 1000))ms\n"

        case .doubleTap(let identifier, let label):
            yaml += "- tapOn:\n"
            if !identifier.isEmpty && identifier != "manual_edge" {
                yaml += "    id: \"\(identifier)\"\n"
            } else if !label.isEmpty {
                yaml += "    text: \"\(label)\"\n"
            }
            yaml += "- tapOn:\n"
            if !identifier.isEmpty && identifier != "manual_edge" {
                yaml += "    id: \"\(identifier)\"\n"
            } else if !label.isEmpty {
                yaml += "    text: \"\(label)\"\n"
            }

        case .tapCoordinate(let x, let y):
            yaml += "- tapOn:\n"
            yaml += "    point: \(Int(x * 100))%,\(Int(y * 100))%\n"

        case .tapCell(let index, _, let label):
            yaml += "- tapOn:\n"
            if !label.isEmpty {
                yaml += "    text: \"\(label)\"\n"
            }
            yaml += "    index: \(index)\n"
        }

        yaml += "\n"
        return yaml
    }
}
